' Gambas module file

Public Sub Main()

  Dim hSettings As Settings
  Dim sPath As String

  For Each sPath In ["/home/benoit/.config/gambas3/gambas3.conf", "/home/benoit/.config/gambas3/gambas3.recent.conf", "/home/benoit/gambas/git/master/app/src/gambas3/.settings", "/home/benoit/.config/gambas3/gambas3-farm.conf"]
    hSettings = New Settings(sPath)
  Next

End

' Private Sub Dump(hSettings As Settings)
' 
'   Dim sSlot As String
'   Dim sKey As String
' 
'   For Each sSlot In hSettings.Keys
'     
'     Print "["; sSlot; "]"
'     For Each sKey In hSettings.Keys[sSlot]
'       Print sKey; "="; hSettings[sSlot &/ sKey]
'     Next
'     
'   Next
'   Print
' 
' End
' 
