' Gambas module file

Public Sub Main()

  Dim hSettings As Settings

  hSettings = New Settings("~/test.conf")
  'hSettings["LipidProfile/VLDL"] = "$Calc[{Triglyceride}/5]"
  'hSettings.Save
  Print hSettings["LipidProfile/VLDL"]

End

' Private Sub Dump(hSettings As Settings)
' 
'   Dim sSlot As String
'   Dim sKey As String
' 
'   For Each sSlot In hSettings.Keys
'     
'     Print "["; sSlot; "]"
'     For Each sKey In hSettings.Keys[sSlot]
'       Print sKey; "="; hSettings[sSlot &/ sKey]
'     Next
'     
'   Next
'   Print
' 
' End
' 
