' Gambas module file

Public Sub Main()

  Dim hClient As MongoClient
  Dim cResult As Collection
  Dim hResult As MongoResult
  Dim cDoc As Collection
  Dim hTable As MongoCollection
  Dim N As Integer
  Dim vVal As Variant
  Dim sId As String
  
  Component.Load("gb.util.web")

  hClient = New MongoClient("mongodb://10.254.16.28")

  'Print hClient.Databases.Join()
  
  hClient.Database = "omogen_test_mongo"

  Print hClient.Collections.Join()

  'hClient["test"].Insert(["_id": "ACT.A", "classe": "activité"])
  'hClient["test"].Insert(["_id": "ACT.B", "classe": "activité"])

  hTable = hClient["test"]
  
  Try hTable.Indexes.Remove("activité_1_nom_1")
  Try hTable.Indexes.Remove("classe_1_nom_1")
  Print hTable.Indexes.Add(["classe": 1, "nom": 1], ["unique": True])
  
  hResult = hTable.Indexes.Query()
  For Each cDoc In hResult
    Print JSON.ToString(cDoc)
  Next
  
  Print JSON.ToString(hTable["ACT.Z"])
  Print JSON.ToString(hTable["ACT.Z2"])
  
  'hTable["ACT.Z"] = ["_id": "ACT.Z", "classe": "activité", "nom": "Activité Zarbi"]
  'hTable["ACT.Z2"] = ["_id": "ACT.Z2", "classe": "activité", "nom": "Activité Zarbi"]
  hTable["ACT.W"] = ["classe": "activité", "état": "Normal"]
  
  Print hTable.Count
  For Each sId In hTable.Find()
    Print JSON.ToString(hTable[sId])
  Next

End
