' Gambas module file

Public Sub Main()

  Dim hJS As TextHighlighter
  Dim hCSS As TextHighlighter
  Dim hHTML As TextHighlighter

  hJS = TextHighlighter.FromFile("./highlight/javascript.highlight")
  hCSS = TextHighlighter.FromFile("./highlight/css.highlight")
  hHTML = TextHighlighter.FromFile("./highlight/html.highlight")
  'File.Save("~/test.html", hTextHighlighter.ToHTML(File.Load("custom/selectr.js")))

  'File.Save("~/test.html", hCSS.ToHTML(File.Load("test/style.css")))
  File.Save("~/test.html", hHTML.ToHTML(File.Load("test/page.html")))

End
