' Gambas module file

Public Sub Main()

  'File.Save("~/test.html", hCSS.ToHTML(File.Load("test/style.css")))
  TextHighlighter.CanRewrite = False
  'File.Save("~/test.html", TextHighlighter["webpage"].ToHTML(File.Load("~/gambas/git/master/comp/src/gb.form.editor/test.html")))
  File.Save("~/test.html", TextHighlighter["cplusplus"].ToHTML(File.Load("~/gambas/git/master/gb.qt5/src/CWidget.cpp")))

End
