' Gambas module file

Public Sub Main()

  Dim hTextHighlighter As TextHighlighter

  hTextHighlighter = TextHighlighter.FromFile("./highlight/javascript.highlight")
  'File.Save("~/test.html", hTextHighlighter.ToHTML(File.Load("custom/selectr.js")))

  hTextHighlighter = TextHighlighter.FromFile("./highlight/html.highlight")
  File.Save("~/test.html", hTextHighlighter.ToHTML(File.Load("custom/page.html")))

End
